spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/talent_recruitment
    username: root
    password: 8476929746@lti
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true